source 'git@git.vipaylife.com:vipay/Chaos-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'HDUIKit_Example' do
  pod 'HDUIKit', :path => '../'
  pod 'Masonry'

  target 'HDUIKit_Tests' do
    inherit! :search_paths


  end
end
