source 'ssh://git@code.kh-super.net:7999/mob/chaos-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'HDUIKit_Example' do
  pod 'HDUIKit', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']

  target 'HDUIKit_Tests' do
    inherit! :search_paths


  end
end
